[package]
name = "png_color_converter"
version = "0.1.0"
edition = "2021"
authors = ["Cade Warg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
png = "0.17.11"
